spring:
  application:
    name: ECommerceApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerceappdb_test11?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto=update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0KB
      max-file-size: 400MB
      max-request-size: 400MB

springdoc:
  swagger-ui:
    doc-expansion: false
    tags-sorter: alpha
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"

project:
  image: images/

logging:
  level:
    org.springframework.security: DEBUG
